version: 2.1jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/reposteps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
